// Automatically generated by build process.

#ifndef BUILD_INFO_HH
#define BUILD_INFO_HH

namespace openmsx {

static const bool OPENMSX_BIGENDIAN = false;

} // namespace openmsx

#endif // BUILD_INFO_HH
