openmsx_sources(
    SOURCES
        AVTFDC.cc
        BootBlocks.cc
        CanonFDC.cc
        DMKDiskImage.cc
        DSKDiskImage.cc
        DirAsDSK.cc
        Disk.cc
        DiskChanger.cc
        DiskContainer.cc
        DiskDrive.cc
        DiskFactory.cc
        DiskImageCLI.cc
        DiskImageUtils.cc
        DiskManipulator.cc
        DiskName.cc
        DiskPartition.cc
        DriveMultiplexer.cc
        DummyDisk.cc
        EmptyDiskPatch.cc
        MSXFDC.cc
        MSXtar.cc
        MicrosolFDC.cc
        NationalFDC.cc
        NowindCommand.cc
        NowindHost.cc
        NowindInterface.cc
        NowindRomDisk.cc
        PhilipsFDC.cc
        RamDSKDiskImage.cc
        RawTrack.cc
        RealDrive.cc
        SVIFDC.cc
        SanyoFDC.cc
        SectorAccessibleDisk.cc
        SectorBasedDisk.cc
        SpectravideoFDC.cc
        TC8566AF.cc
        TalentTDC600.cc
        ToshibaFDC.cc
        TurboRFDC.cc
        VictorFDC.cc
        WD2793.cc
        WD2793BasedFDC.cc
        XSADiskImage.cc
        XSAExtractor.cc
        YamahaFDC.cc
)
