#!/bin/sh -e
##  by Joost Yervante Damad <joost@lumatec.be>
##
## DP: fix wrong name m86k

case "$1" in
       -patch) cp -f build/cpu-m86k.mk build/cpu-m68k.mk ;;
       -unpatch) rm -f build/cpu-m68k.mk ;;
        *)
                echo >&2 "`basename $0`: script expects -patch|-unpatch as argument"
                exit 1;;
esac

exit 0
