#!/bin/sh -e
##  by Joost Yervante Damad <joost@lumatec.be>
##

if [ $# -ne 1 ]; then
    echo >&2 "`basename $0`: script expects -patch|-unpatch as argument"
    exit 1
fi

[ -f debian/patches/00patch-opts ] && . debian/patches/00patch-opts
patch_opts="${patch_opts:--f --no-backup-if-mismatch}"

case "$1" in
       -patch) patch $patch_opts -p1 < $0;;
       -unpatch) patch $patch_opts -p1 -R < $0;;
        *)
                echo >&2 "`basename $0`: script expects -patch|-unpatch as argument"
                exit 1;;
esac

exit 0

@DPATCH@
--- openmsx-0.6.2.orig/src/input/Keyboard.cc	2007-08-10 20:13:30.000000000 +0200
+++ openmsx-0.6.2/src/input/Keyboard.cc	2007-08-10 20:22:55.000000000 +0200
@@ -192,17 +192,7 @@
 		const KeyEvent& keyEvent = checked_cast<const KeyEvent&>(*event);
 		Keys::KeyCode key = static_cast<Keys::KeyCode>
 			(int(keyEvent.getKeyCode()) & int(Keys::K_MASK));
-		if (key != Keys::K_CAPSLOCK) {
-			processKey(type == OPENMSX_KEY_DOWN_EVENT, key);
-		} else {
-			// This is a workaround for a SDL 'feature' (it's
-			// actually a documented bug in SDL). In a future
-			// refactoring this workaround should be moved to a
-			// higher level.
-			processKey(true, Keys::K_CAPSLOCK);
-			Clock<1000> now(getScheduler().getCurrentTime());
-			setSyncPoint(now + 100);
-		}
+		processKey(type == OPENMSX_KEY_DOWN_EVENT, key);
 	}
 }
 
