.\"                              hey, Emacs:   -*- nroff -*-
.TH OPENMSX 1 "May 4, 2001"
.\" Please update the above date whenever this man page is modified.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins (default)
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
openmsx \- Emulate the MSX standard.
.SH SYNOPSIS
.B openmsx
.RI [ options ]
.SH DESCRIPTION
\fBopenmsx\fP washes your windows, mends your fences, mows your lawn...
.PP
It also...
.SH OPTIONS
\fBopenmsx\fP accepts the following options:
.TP
.BR  -q , " --quiet" , " --silent"
Inhibit usual output.
.TP
.B  -v, --verbose
Print more information.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-V, \-\-version
Show version of program.
.\" .SH "SEE ALSO"
.\" .BR foo (1), 
.\" .BR bar (1).
.SH AUTHOR
David Heremans <david.heremans@gnu-linux.net>,
Wouter Vermaelen <wouter.vermaelen@student.kuleuven.ac.be>,
Alex Wulms <awulms@inter.nl.net>,
Joost Yervante Damad <j.damad@qahwah.net>.

