openmsx_sources(
    SOURCES
        RomPageNN.cc
        RomNational.cc
        MSXMegaRam.cc
        RomAlAlamiah30in1.cc
        RomAscii16X.cc
        MSXRam.cc
        RomSuperSwangi.cc
        RomMatraCompilation.cc
        RomManbow2.cc
        RomAscii16_2.cc
        RomHolyQuran2.cc
        SdCard.cc
        MSXRom.cc
        RomBlocks.cc
        Rom.cc
        MSXMemoryMapperBase.cc
        RomDatabase.cc
        RomMajutsushi.cc
        MSXRomCLI.cc
        MegaFlashRomSCCPlusSD.cc
        ColecoSuperGameModule.cc
        MSXMemoryMapper.cc
        AmdFlash.cc
        RomGeneric16kB.cc
        RomPadial8kB.cc
        TrackedRam.cc
        RomSynthesizer.cc
        EEPROM_93C46.cc
        SRAM.cc
        RomDooly.cc
        RomZemina80in1.cc
        RomFactory.cc
        RomFSA1FM.cc
        ESE_RAM.cc
        RomMatraInk.cc
        RomAscii8_8.cc
        PanasonicRam.cc
        RomPlayBall.cc
        RomArc.cc
        RomMitsubishiMLTS2.cc
        RomInfo.cc
        FraelSwitchableROM.cc
        MSXMapperIO.cc
        RomKonami.cc
        RomDRAM.cc
        RomRamFile.cc
        MSXHBI55.cc
        RomGameMaster2.cc
        RomRType.cc
        RomCrossBlaim.cc
        RomMultiRom.cc
        RomZemina126in1.cc
        Ram.cc
        RomNeo8.cc
        RomGeneric8kB.cc
        RomAscii16kB.cc
        RomKonamiKeyboardMaster.cc
        Carnivore2.cc
        RomMSXWrite.cc
        RomZemina25in1.cc
        RomPlain.cc
        MSXMirrorDevice.cc
        PanasonicMemory.cc
        RomPanasonic.cc
        ROMHunterMk2.cc
        MusicalMemoryMapper.cc
        RomSuperLodeRunner.cc
        RomHolyQuran.cc
        MegaFlashRomSCCPlus.cc
        RomColecoMegaCart.cc
        ReproCartridgeV2.cc
        Yamanooto.cc
        RomPadial16kB.cc
        RomAscii8kB.cc
        RomMSXtra.cc
        RomRetroHard31in1.cc
        RomInfoTopic.cc
        ReproCartridgeV1.cc
        KonamiUltimateCollection.cc
        CheckedRam.cc
        RomMSXDOS2.cc
        RomZemina90in1.cc
        RomKonamiSCC.cc
        RomHalnote.cc
        RomNeo16.cc
        CanonWordProcessor.cc
        ESE_SCC.cc
        MSXPac.cc
        RomHarryFox.cc
        RomNettouYakyuu.cc
)
