openmsx_sources(
    SOURCES
        AY8910.cc
        AY8910Periphery.cc
        AudioInputConnector.cc
        AudioInputDevice.cc
        BlipBuffer.cc
        DACSound16S.cc
        DACSound8U.cc
        DalSoRiR2.cc
        DummyAudioInputDevice.cc
        DummyY8950KeyboardDevice.cc
        EmuTimer.cc
        KeyClick.cc
        MSXAudio.cc
        MSXFmPac.cc
        MSXMixer.cc
        MSXMoonSound.cc
        MSXMusic.cc
        MSXOPL3Cartridge.cc
        MSXPSG.cc
        MSXSCCPlusCart.cc
        MSXTurboRPCM.cc
        MSXYamahaSFG.cc
        Mixer.cc
        NullSoundDriver.cc
        ResampleBlip.cc
        ResampleHQ.cc
        ResampleTrivial.cc
        ResampledSoundDevice.cc
        SCC.cc
        SDLSoundDriver.cc
        SN76489.cc
        SNPSG.cc
        SVIPSG.cc
        SamplePlayer.cc
        SoundDevice.cc
        VLM5030.cc
        WavAudioInput.cc
        WavWriter.cc
        Y8950.cc
        Y8950Adpcm.cc
        Y8950KeyboardConnector.cc
        Y8950KeyboardDevice.cc
        Y8950Periphery.cc
        YM2151.cc
        YM2413.cc
        YM2413Burczynski.cc
        YM2413NukeYKT.cc
        YM2413Okazaki.cc
        YM2413OriginalNukeYKT.cc
        YMF262.cc
        YMF278.cc
        YMF278B.cc
        opll.cc
)
