openmsx_sources(
    SOURCES
        DebuggableEditor.cc
        FileListWidget.cc
        ImGuiAdjust.cc
        ImGuiBitmapViewer.cc
        ImGuiBreakPoints.cc
        ImGuiCharacter.cc
        ImGuiCheatFinder.cc
        ImGuiConnector.cc
        ImGuiConsole.cc
        ImGuiDebugger.cc
        ImGuiDisassembly.cc
        ImGuiDiskManipulator.cc
        ImGuiHelp.cc
        ImGuiKeyboard.cc
        ImGuiLayer.cc
        ImGuiMachine.cc
        ImGuiManager.cc
        ImGuiMedia.cc
        ImGuiMessages.cc
        ImGuiOpenFile.cc
        ImGuiOsdIcons.cc
        ImGuiPalette.cc
        ImGuiReverseBar.cc
        ImGuiSCCViewer.cc
        ImGuiSettings.cc
        ImGuiSoundChip.cc
        ImGuiSpriteViewer.cc
        ImGuiSymbols.cc
        ImGuiTools.cc
        ImGuiTrainer.cc
        ImGuiUtils.cc
        ImGuiVdpRegs.cc
        ImGuiWatchExpr.cc
        ImGuiWaveViewer.cc
        Shortcuts.cc
)
