openmsx_sources(
    SOURCES
        Autofire.cc
        CLIOption.cc
        CartridgeSlotManager.cc
        ChakkariCopy.cc
        CliExtension.cc
        CommandLineParser.cc
        Connector.cc
        DebugDevice.cc
        DeviceFactory.cc
        DummyDevice.cc
        DummyPrinterPortDevice.cc
        DynamicClock.cc
        EmptyPatch.cc
        EmuTime.cc
        FirmwareSwitch.cc
        GlobalSettings.cc
        I8255.cc
        IPSPatch.cc
        LedStatus.cc
        MSXBunsetsu.cc
        MSXCielTurbo.cc
        MSXDevice.cc
        MSXDeviceSwitch.cc
        MSXE6Timer.cc
        MSXHiResTimer.cc
        MSXKanji.cc
        MSXKanji12.cc
        MSXMatsushita.cc
        MSXMotherBoard.cc
        MSXPPI.cc
        MSXPrinterPort.cc
        MSXRTC.cc
        MSXResetStatusRegister.cc
        MSXS1985.cc
        MSXS1990.cc
        MSXSwitchedDevice.cc
        MSXToshibaTcx200x.cc
        MSXTurboRPause.cc
        MSXVictorHC9xSystemControl.cc
        PasswordCart.cc
        Pluggable.cc
        PluggableFactory.cc
        PluggingController.cc
        Printer.cc
        PrinterPortDevice.cc
        PrinterPortLogger.cc
        PrinterPortSimpl.cc
        ProgrammableDevice.cc
        RP5C01.cc
        RTSchedulable.cc
        RTScheduler.cc
        Reactor.cc
        RealTime.cc
        RenShaTurbo.cc
        ReplayCLI.cc
        ReverseManager.cc
        SC3000PPI.cc
        SG1000Pause.cc
        SVIPPI.cc
        SVIPrinterPort.cc
        SaveStateCLI.cc
        Schedulable.cc
        Scheduler.cc
        SensorKid.cc
        SpeedManager.cc
        ThrottleManager.cc
        Version.cc
        YamahaSKW01.cc
        serialize.cc
        serialize_core.cc
        serialize_meta.cc
    SUBDIRS
        3rdparty
        cassette
        commands
        config
        console
        cpu
        debugger
        events
        fdc
        file
        ide
        imgui
        input
        laserdisc
        memory
        security
        serial
        settings
        sound
        thread
        utils
        video
)

if (OPENMSX_UNITTEST)
    openmsx_sources(SUBDIRS unittest)
else()
    openmsx_sources(SOURCES main.cc)
endif()
