openmsx_sources(
    SOURCES
        AdhocCliCommParser_test.cc
        Base64_test.cc
        BooleanInput_test.cc
        CRC16_test.cc
        CircularBuffer_test.cc
        ConsoleLine_test.cc
        Dasm_test.cc
        Date_test.cc
        DivMod_test.cc
        FileOperations_test.cc
        FilePoolCore_test.cc
        FixedPoint_test.cc
        HexDump_test.cc
        IterableBitSet_test.cc
        Keys_test.cc
        Math_test.cc
        MemoryBufferFile.cc
        MemoryBufferFile_test.cc
        ObjectPool_test.cc
        ScopedAssign_test.cc
        SimpleHashSet_test.cc
        StringOp_test.cc
        StringReplacer_test.cc
        SymbolManager_test.cc
        TclArgParser.cc
        TclObject_test.cc
        TigerTree_test.cc
        WavData_test.cc
        XMLEscape_test.cc
        XMLOutputStream_test.cc
        circular_buffer_test.cc
        eeprom.cc
        endian_test.cc
        enumerate_test.cc
        escape_newline_test.cc
        gl_mat.cc
        gl_transform.cc
        gl_vec.cc
        join_test.cc
        main.cc
        monotonic_allocator_test.cc
        narrow_test.cc
        ranges_test.cc
        semiregular_test.cc
        sha1.cc
        static_string_view_test.cc
        stl_test.cc
        strCat.cc
        view_test.cc
        xrange_test.cc
)
