#!/bin/bash

IFS=\

echo "<?xml version=\"1.0\"?>"
echo "<!DOCTYPE romdb SYSTEM \"romdb.dtd\">"
echo
echo "<romdb>"
echo
for I in $@; do
	echo "  <rom id=\"$I\">"
	echo "    <md5>`md5sum $I | cut -f1 -d\ `</md5>"
	echo "    <romtype>auto</romtype>"
	echo "  </rom>"
	echo
done
echo "</romdb>"
